# Generated by Django 4.2 on 2025-08-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_userid_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='disliked_ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_ingredients',
            field=models.TextField(blank=True),
        ),
    ]
