# Generated by Django 4.2 on 2025-09-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_customuser_disliked_ingredients_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="allergies",
            field=models.TextField(blank=True, help_text="쉼표(,)로 구분된 알레르기 재료"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_vegan",
            field=models.BooleanField(default=False, help_text="비건 여부"),
        ),
    ]
