# Generated by Django 4.2 on 2025-10-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customuser_allergies_customuser_is_vegan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='voice_name',
            field=models.CharField(blank=True, help_text='TTS 목소리 이름', max_length=150, null=True),
        ),
    ]
