# Generated by Django 4.2 on 2025-09-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("ingredients", models.JSONField()),
                ("steps", models.JSONField()),
            ],
        ),
    ]
